Req edit
mattjegan/HowLong pull request #32
Opened 2017-10-09 20:33 UTC by aniketrege

Updated requirements.txt file for pip installation

2017-10-11 00:13 UTC, mattjegan commented on HowLong/HowLong.py
> +        logging.debug(colored("Running " + readable_command), 'green')
This needs to be `logging.debug(colored("Running " + readable_command, 'green'))`

2017-10-11 00:14 UTC, mattjegan commented on HowLong/HowLong.py
> +        logging.debug(colored("Finished " + readable_command), 'red')
This needs to be: `logging.debug(colored("Finished " + readable_command, 'red'))`

2017-10-11 00:14 UTC, mattjegan requested changes
Looks pretty good to me, just a few typos that need fixing before I can merge. Thanks 😄

2017-10-12 10:10 UTC, aniketrege commented
Hey Matt, I've fixed those typos for you

2017-10-12 22:18 UTC, mattjegan approved these changes

2017-10-12 22:23 UTC, merged